name: carpool_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.12.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_dotenv: ^5.0.2
  google_place: ^0.4.7
  http: ^0.13.4
  google_maps_flutter: 
  google_maps_flutter_web: ^0.5.4+3
  flutter_polyline_points: ^1.0.0
  firebase_core: ^2.24.2
  geolocator: ^10.1.0
  shared_preferences: ^2.0.13
  uuid: ^4.2.2
  provider: ^6.0.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  cloud_firestore_web: ^3.9.0
  progress_indicators: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
